# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftTest' do
  use_frameworks!

    pod 'RxSwift',    '~> 3.0'
    pod 'RxCocoa',    '~> 3.0'
    pod 'RxBlocking', '~> 3.0'
    pod 'RxTest',     '~> 3.0'

end
